// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAmqU6OGUGf_bw4oLGN5HT-bAlmLpYuw8',
    appId: '1:225432835586:web:d7432bcbfde1c9da00f91b',
    messagingSenderId: '225432835586',
    projectId: 'first-app-54483',
    authDomain: 'first-app-54483.firebaseapp.com',
    databaseURL: 'https://first-app-54483-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-54483.appspot.com',
    measurementId: 'G-4Y2LE97NVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgUs5_r4pF63Q5IKp9rf49YrzJRhVa2tQ',
    appId: '1:225432835586:android:2a4277acb395d5e600f91b',
    messagingSenderId: '225432835586',
    projectId: 'first-app-54483',
    databaseURL: 'https://first-app-54483-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-54483.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASNZXeYPSu84yhuZlKw64h45pOespX3-8',
    appId: '1:225432835586:ios:4d85d19a88c1a5da00f91b',
    messagingSenderId: '225432835586',
    projectId: 'first-app-54483',
    databaseURL: 'https://first-app-54483-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-54483.appspot.com',
    iosBundleId: 'com.example.karyawannApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASNZXeYPSu84yhuZlKw64h45pOespX3-8',
    appId: '1:225432835586:ios:41640ce4a24170d800f91b',
    messagingSenderId: '225432835586',
    projectId: 'first-app-54483',
    databaseURL: 'https://first-app-54483-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-54483.appspot.com',
    iosBundleId: 'com.example.karyawannApp.RunnerTests',
  );
}
